export const mapping_en = {
  login: 'login now',
  login_social_media: 'Login with facebook or other social media',
  password: 'Password',
  your_email: 'Your email',
  login_description:
    'Enter your email address and password in order to login. If you have logged in via facebook or other services, click "Other login options"',
  create_account_with_email: 'Create account with my email',
  login_account: 'Login Account',
  login_button: 'Login',
  provide_email: 'You need to provide email',
  provide_password: 'You need to provide password',
  provide_firstname: 'firstname is necessary',
  provide_lastname: 'lastname is necessary',
  provide_phone: 'phone is necessary',
  provide_correct_email: 'your email is not valid',
  provide_password_min_6: 'minimum length should be 6 character',
  provide_password_confirm: 'confirm password is necessary',
  provide_password_mismatch: 'password and confirm password are not match',
  filter: 'Filter',
  tap_to_search: 'Tap to search...',
  search_focus_hint: 'Search a boat name, model...',
  back: 'Go back',
  login_header:
    'Login with your favorite account, if you don\'t have any account yet, click on "Sign Up Now".',
  login_profile_header: 'To access your profile, you need to login',
  login_user_yachts_header:
    'Please login to your account, and then we will show your yacht listing here.',
  login_yacht_form_header: 'To create a yacht, you need to login',
  no_result: 'We cannot find any result for your filters!',
  keyword_placeholder: 'Boat name, model, type...',

  no_internet_connection: 'No Internet Connection',
  boat_name: 'Boat name, model or title',
  boat_price: 'Price of the boat %sample_price%',
  marked_field: 'Please check the marked fields and complete them',
  boat_general_info: 'Boat general information',
  equipments_on_board: 'Equipments on the board',
  update_boat: 'Update boat',
  save_boat: 'Save boat',
  boat_save_terms:
    'By saving the boat information, it will be visible to public. Make sure you have read the "Service code" on PixelPlux website.',
  images_count: 'Images (%count%)',
  select_location: 'Select location',
  technical_info: 'Technical information',
  required_license: 'Does sailor of this boat require a license?',
  boat_has_trailer: 'Does boat include a trailor also?',
  boat_operation_status:
    'Does the vessel have all equipments working seamlessly?',
  my_boats: 'My boats',
  favorite_list: 'Favorite list',
  no_location: 'Unknown location',
  apply_filters: 'Apply filters',
  location: 'Location',
  filter_keyword_placeholder: 'Boat name, type or model',
  price_range: 'Price range',
  price_from: 'From',
  price_to: 'To',
  reset_filters: 'Reset all filters',
  cancel: 'Cancel',
  location_search_placeholder: 'Country, town, city...',
  bimini: 'Bimini',

  option_equipment_bimini: 'Bimini',
  option_navigation_outboard: 'Outboard',
  option_equipment_bathing_ladder: 'Bathing ladder',
  option_navigation_outboard_motor: 'Outboard motor',
  option_navigation_bow_thruster: 'Bow thruster',
  option_equipment_dining_table: 'Dining table',
  option_navigation_electric_windlass: 'Electric windlass',
  option_equipment_bow_sundeck: 'Bow sundeck',
  option_navigation_gps: 'GPS',
  option_equipment_deck_shower: 'Deck shower',
  option_navigation_depth_sounder: 'Depth sounder',
  option_navigation_vhf: 'VHF',
  option_navigation_automatic_pilot: 'Automatic pilot',
  option_kitchen_freezer: 'Freezer',
  option_energy_220v_socket: '220V socket',
  option_kitchen_oven: 'Oven',
  option_energy_usb: 'USB',
  option_kitchen_refrigerator: 'Refrigerator',
  option_kitchen_sink: 'Sink',
  outdoor_equipment: 'Outdoor equipment',
  navigation_equipment: 'Navigation equipment',
  energy: 'Energy',
  kitchen: 'Kitchen',
  image_select_title: 'Tap to select a photo. Tap on photo to edit.',
  yes: 'Yes',
  no: 'No',
  price_for: 'Price for %price%',
  filters: 'Filters',
  view_my_boats: 'View my boats',
  sign_out: 'Sign Out',
  edit_profile: 'Edit your profile',
  language: 'Language:',
  lang_en: 'English',
  lang_pl: 'Polish (Polski)',
  lang_ru: 'Russian (русский)',
  your_currency: 'Your currency:',
  update_profile: 'Update Profile',
  back_to_profile: 'Or back to profile',
  confirm_password: 'Confirm password',
  phone: 'Phone',
  last_name: 'Last name',
  first_name: 'First name',
  change_picture: 'Change Picture',
  other_login_options: 'Other login options',
  login_with_email: 'Login with your existing email',

  signup_screen_title:
    'Enter required information to create new account, or login via click "Other login options"',
  create_account: 'Create Account',
  try_again_later: 'Please try again later',
  account_been_created: 'Your account has been created %name%!',
  something_went_wrong: "Something wen't wrong, try again later",
  accept_terms: 'Please accept the terms first',
  confirm: 'Confirm',
  accept: 'Accept',
  terms_of_use: 'Terms of Use',
  and: 'and',
  privacy_policy: 'Privacy Policy',
  connect_with_facebook: 'Connect with Facebook',
  conenct_with_google: 'Connect with Google',
  by_continue_you_agree: "I'd agree with terms and conditions",
  facebook_cannot_login: 'We cannot login via facebook',
  boat_type_form: 'Boat type (structure)',
  vessel_length_form: 'Boat length (meters)',
  engine_hp_form: 'Engine horsepower',
  there_are_no_boats_fav:
    'You did not select any boat yet. Click on the "Heart button" on any boat to keep them here.',
  call_number: 'Call number',
  text_message: 'Text message',
  copy_number: 'Copy number',
  yacht_single_num_click: 'What to do with number?',
  boat_text_message_template:
    'Hello %recipient%, I am interested in "%title%". Regards, %sender%',
  visitor_from_dokayak: 'visitor from dokayak',
  map_selected_location: 'Selected location',
  boat_type_necessary: 'Boat type is necessary to be selected',
  boat_name_necessary: 'Yacht name is necessary.',
  at_least_one_image:
    'At least one image is needed. Add 5 or more images to impact audience better.',
  boat_price_necessary: 'Yacht price is necessary.',
  phone_is_necessary: 'Contact number is necessary so people can contact you',
  boat_license_necessary:
    'Boat license type is necessary. If crew require to have a license, please select "Yes". Otherwise choose "No"',
  boat_trailer_necessary:
    'If you have a trailer, please select "Yes". Many people interested to know if you can provide a trailer.',
  boat_operation_status_necessary:
    'Boat status helps to get better target. If the boat is ready to sail without any repair, select "Yes".',
  boat_having_errors:
    'Yacht information needs to be completed, please check some fields having error',
  current_and_original_currency_warning:
    "This ad currency is (%original_currency%) and different than your current currency. If you don't change currency, it won't be changed.",
  account_picture_successfully_updated: 'Your account picture has been updated',
  cannot_upload_picture: 'We cannot upload this image',
  account_been_updated: 'Your account has been updated %name%!',
  currency_notice:
    'If you do not find your currency/language, select most popular currency (Euro/USD) to you.',
  please_select_localisation_initial:
    'It would be perfect to set your currency and country in the begining.',
  set_and_continue: 'Set and continue',
  engine_stroke_form: 'Engine strokes (2/4)',
  boat_current_env_form: 'Boat current environment',
  sleeping_capacity_form: 'Sleeping capacity (beds)',
  boat_launch_option_form: 'Boat launch status',
  _4_stroke_engine: '4 Stroke engine',
  _2_stroke_engine: '2 Stroke engine',
  can_be_moved_to_ground: 'Yes, Can be launched on the water',
  cannot_be_moved_to_ground: 'No, Cannot be launched on the water',
  on_the_ground: 'On the ground',
  on_the_water: 'On the water',
  boat_on_board_capacity_form: 'Boat onboard capacity',
  boat_engine_info: 'Boat engine info',
  boat_cabin_info: 'Boat cabin info',
  boat_testing_info: 'Boat testing and launch',
  pick_photo_from: 'Pick photo from...',
  take_photo_camera: 'Take photo (Camera)',
  gallery: 'Gallery',
  mine: 'Mine',
  home_screen: 'Boats',
  new_screen: 'Add',
  profile_screen: 'Profile',
  favorites_screen: 'Favorites',
  e_permission_missing:
    'Permission to take picture or gallery needed. You may need to go to phone "settings" and give permission to dokayak',
  boat_construction_year_form: 'Construction year',
  vessel_width_form: 'Boat width (meters)',
  'meter_match_00.00': 'Tylko pływak, z wyjątkiem 10.5',
  user_yachts_empty:
    "You don't have any boats. Touch add icon below to add yours"
};
